services:

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: sum-org-frontend
    restart: unless-stopped

    networks:
      - ${NETWORK_NAME}

    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: sum-org-nginx
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - frontend

    networks:
      - ${NETWORK_NAME}

networks:
  network_name:
    external: true